#  AI-Based Automated Financial Report Generation System

This project predicts company net profit using XGBoost and LightGBM and generates automated financial reports.

## Step 1 — Install & Import Libraries

In [1]:
!pip install google-generativeai reportlab xgboost lightgbm -q

import warnings; warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing   import LabelEncoder
from sklearn.metrics         import mean_absolute_error, mean_squared_error, r2_score

import xgboost  as xgb
import lightgbm as lgb

import google.generativeai as genai

from reportlab.lib.pagesizes import A4
from reportlab.lib           import colors
from reportlab.lib.styles    import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units     import inch
from reportlab.platypus      import (SimpleDocTemplate, Paragraph, Spacer,
                                      Table, TableStyle, PageBreak,
                                      HRFlowable, Image as RLImage)
from reportlab.lib.enums     import TA_CENTER, TA_JUSTIFY

print("Completed")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 23.1 MB/s eta 0:00:00
Completed

## Step 2 — Generate Dataset
275 companies · 5 sectors · 4 regions · 2019–2023
The dataset is generated automatically — no file upload needed.

In [2]:
np.random.seed(42)

N       = 275
SECTORS = ["Technology","Healthcare","Finance","Energy","Retail"]
REGIONS = ["North America","Europe","Asia Pacific","Latin America"]
RATINGS = ["AAA","AA","A","BBB","BB","B"]
RATING_PROBS = [0.05, 0.10, 0.20, 0.35, 0.20, 0.10]

revenue      = np.random.uniform(50, 5000, N).round(2)
cogs         = (revenue * np.random.uniform(0.35, 0.65, N)).round(2)
gross_profit = (revenue - cogs).round(2)
op_expenses  = (revenue * np.random.uniform(0.15, 0.35, N)).round(2)
ebit         = (gross_profit - op_expenses).round(2)
interest_exp = (revenue * np.random.uniform(0.01, 0.08, N)).round(2)
ebt          = (ebit - interest_exp).round(2)
net_profit   = (ebt * (1 - np.random.uniform(0.15, 0.30, N))).round(2)
total_assets = (revenue * np.random.uniform(1.0, 3.5, N)).round(2)
total_debt   = (total_assets * np.random.uniform(0.20, 0.60, N)).round(2)
equity       = (total_assets - total_debt).round(2)
employees    = np.random.randint(100, 50000, N)
market_cap   = (revenue * np.random.uniform(1.5, 8.0, N)).round(2)

for arr in [net_profit, total_debt, op_expenses, market_cap]:
    arr[np.random.choice([True,False], N, p=[0.05,0.95])] = np.nan

df = pd.DataFrame({
    "Company":       [f"Company_{i:03d}" for i in range(1, N+1)],
    "Year":          np.random.choice(range(2019, 2024), N),
    "Sector":        np.random.choice(SECTORS, N),
    "Region":        np.random.choice(REGIONS, N),
    "Revenue":       revenue,      "COGS":         cogs,
    "Gross_Profit":  gross_profit, "Op_Expenses":  op_expenses,
    "EBIT":          ebit,         "Interest_Exp": interest_exp,
    "EBT":           ebt,          "Net_Profit":   net_profit,
    "Total_Assets":  total_assets, "Total_Debt":   total_debt,
    "Equity":        equity,       "Employees":    employees,
    "Market_Cap":    market_cap,
    "Credit_Rating": np.random.choice(RATINGS, N, p=RATING_PROBS),
})

df.to_csv("financial_dataset.csv", index=False)
print(f" Dataset generated  →  {df.shape[0]} rows × {df.shape[1]} columns")
print(f"   Years   : {sorted(df['Year'].unique())}")
print(f"   Sectors : {df['Sector'].unique().tolist()}")
df.head()

 Dataset generated  →  275 rows × 18 columns
   Years   : [np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023)]
   Sectors : ['Finance', 'Energy', 'Technology', 'Healthcare', 'Retail']

,Company,Year,Sector,Region,Revenue,COGS,Gross_Profit,Op_Expenses,EBIT,Interest_Exp,EBT,Net_Profit,Total_Assets,Total_Debt,Equity,Employees,Market_Cap,Credit_Rating
0,Company_001,2022,Finance,Asia Pacific,1903.97,952.85,951.12,483.67,467.45,141.64,325.81,274.11,6048.67,1297.22,4751.45,15479,7756.41,AA
1,Company_002,2022,Energy,North America,4756.04,2803.63,1952.41,1524.01,428.40,162.87,265.53,187.10,10050.76,3228.82,6821.94,27866,35423.39,BB
2,Company_003,2021,Technology,North America,3673.37,2001.95,1671.42,956.48,714.94,125.95,588.99,422.56,8401.16,2564.41,5836.75,43690,18237.13,AA
3,Company_004,2022,Healthcare,Europe,3013.36,1689.26,1324.10,790.07,534.03,185.70,348.33,247.61,5719.61,1967.86,3751.75,2663,7613.88,B
4,Company_005,2020,Healthcare,North America,822.29,484.11,338.18,267.52,70.66,34.25,36.41,25.51,2041.23,479.81,1561.42,36160,4952.94,A

## Step 3 — Data Understanding

In [4]:
print(f"Shape: {df.shape[0]} rows × {df.shape[1]} columns\n")
df.info()

Shape: 275 rows × 18 columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275 entries, 0 to 274
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company        275 non-null    object
 1   Year           275 non-null    int64
 2   Sector         275 non-null    object
 3   Region         275 non-null    object
 4   Revenue        275 non-null    float64
 5   COGS           275 non-null    float64
 6   Gross_Profit   275 non-null    float64
 7   Op_Expenses    265 non-null    float64
 8   EBIT           275 non-null    float64
 9   Interest_Exp   275 non-null    float64
 10  EBT            275 non-null    float64
 11  Net_Profit     261 non-null    float64
 12  Total_Assets   275 non-null    float64
 13  Total_Debt     256 non-null    float64
 14  Equity         275 non-null    float64
 15  Employees      275 non-null    int64
 16  Market_Cap     261 non-null    float64
 17  Credit_Rating  275 non-null    object
dtypes: float64(12), int64(2), object(4)
memory usage: 38.8+ KB

In [5]:
df.describe().round(2)

,Year,Revenue,COGS,Gross_Profit,Op_Expenses,EBIT,Interest_Exp,EBT,Net_Profit,Total_Assets,Total_Debt,Equity,Employees,Market_Cap
count,275.00,275.00,275.00,275.00,265.00,275.00,275.00,275.00,261.00,275.00,256.00,275.00,275.00,261.00
mean,2021.04,2521.80,1287.44,1234.37,623.52,611.79,110.65,501.14,379.68,5832.29,2342.73,3505.78,23671.85,11815.78
std,1.43,1464.87,803.13,749.36,396.35,454.90,87.06,411.75,317.37,4117.45,1833.56,2588.25,14465.99,8741.43
min,2019.00,75.05,28.12,33.94,17.33,4.91,1.20,-118.19,-89.18,150.92,45.41,77.94,197.00,287.66
25%,2020.00,1241.50,566.74,616.64,294.24,265.31,44.00,183.87,137.20,2371.16,896.56,1328.54,10991.50,5270.41
50%,2021.00,2584.86,1229.98,1186.05,607.09,520.71,89.59,402.88,304.88,4905.13,1848.78,3090.19,22769.00,9731.87
75%,2022.00,3817.96,1933.84,1786.26,891.26,907.14,153.34,724.26,542.91,8744.04,3539.78,5169.49,34611.00,17414.60
max,2023.00,4950.77,3099.07,3030.72,1584.46,2228.90,359.17,1973.68,1526.24,16631.91,9703.83,11439.41,49923.00,37509.69

In [6]:
missing = df.isnull().sum()
missing = missing[missing > 0]
print("Columns with missing values:")
print(missing.to_string())

missing.plot(kind="bar", color="tomato", figsize=(7,4), edgecolor="black")
plt.title("Missing Values per Column", fontsize=13, fontweight="bold")
plt.ylabel("Missing Count"); plt.xticks(rotation=0); plt.tight_layout(); plt.show()

Columns with missing values:
Op_Expenses    10
Net_Profit     14
Total_Debt     19
Market_Cap     14

## Step 4 — Data Preprocessing

In [7]:
for col in df.select_dtypes(include=np.number).columns:
    df[col].fillna(df[col].median(), inplace=True)

before = len(df)
df.drop_duplicates(inplace=True)
df["Year"]      = df["Year"].astype(int)
df["Employees"] = df["Employees"].astype(int)

print(f" Missing values remaining : {df.isnull().sum().sum()}")
print(f" Duplicate rows removed   : {before - len(df)}")
print(f" Final dataset shape      : {df.shape}")

 Missing values remaining : 0
 Duplicate rows removed   : 0
 Final dataset shape      : (275, 18)

## Step 5 — Feature Engineering

| New Column | Formula | Meaning |
|---|---|---|
| `Profit_Margin` | Net Profit ÷ Revenue | Profit per dollar of revenue |
| `Debt_Ratio` | Total Debt ÷ Total Assets | Leverage level |
| `ROA` | Net Profit ÷ Total Assets | Asset efficiency |

In [8]:
df["Profit_Margin"] = (df["Net_Profit"] / df["Revenue"]).round(4)
df["Debt_Ratio"]    = (df["Total_Debt"]  / df["Total_Assets"]).round(4)
df["ROA"]           = (df["Net_Profit"]  / df["Total_Assets"]).round(4)

print(" New features: Profit_Margin, Debt_Ratio, ROA")
df[["Company","Year","Revenue","Net_Profit","Profit_Margin","Debt_Ratio","ROA"]].head(8)

 New features: Profit_Margin, Debt_Ratio, ROA

       Company  Year  Revenue  Net_Profit  Profit_Margin  Debt_Ratio     ROA
0  Company_001  2022  1903.97      274.11         0.1440      0.2145  0.0453
1  Company_002  2022  4756.04      187.10         0.0393      0.3213  0.0186
2  Company_003  2021  3673.37      422.56         0.1150      0.3052  0.0503
3  Company_004  2022  3013.36      247.61         0.0822      0.3441  0.0433
4  Company_005  2020   822.29       25.51         0.0310      0.2351  0.0125
5  Company_006  2023   822.17       85.74         0.1043      0.5748  0.0740
6  Company_007  2023   337.51       88.09         0.2610      0.4215  0.1320
7  Company_008  2020  4337.57     1155.16         0.2663      0.3222  0.0778

## Step 6 — Encode Categorical Columns

In [9]:
le = LabelEncoder()
df["Sector_Code"] = le.fit_transform(df["Sector"])
df["Region_Code"] = le.fit_transform(df["Region"])
df["Credit_Code"] = le.fit_transform(df["Credit_Rating"])

for col, enc in [("Sector","Sector_Code"),("Region","Region_Code"),("Credit_Rating","Credit_Code")]:
    mapping = df[[col,enc]].drop_duplicates().sort_values(enc)
    print(f"{col} encoding:")
    print(mapping.to_string(index=False)); print()

Sector encoding:
    Sector  Sector_Code
    Energy            0
   Finance            1
Healthcare            2
    Retail            3
Technology            4

Region encoding:
       Region  Region_Code
 Asia Pacific            0
       Europe            1
Latin America            2
North America            3

Credit_Rating encoding:
Credit_Rating  Credit_Code
            A            0
           AA            1
          AAA            2
            B            3
           BB            4
          BBB            5

## Step 7 — Exploratory Data Analysis (EDA)

In [10]:
fig, axes = plt.subplots(2, 3, figsize=(15,8))
cols  = ["Revenue","Net_Profit","Gross_Profit","Op_Expenses","Profit_Margin","ROA"]
clrs  = ["steelblue","seagreen","coral","goldenrod","mediumpurple","tomato"]

for ax, col, c in zip(axes.flatten(), cols, clrs):
    ax.hist(df[col], bins=30, color=c, edgecolor="white", linewidth=0.4)
    ax.axvline(df[col].mean(), color="black", linestyle="--", linewidth=1.2, label="Mean")
    ax.set_title(col.replace("_"," "), fontsize=12, fontweight="bold")
    ax.set_xlabel("Value (USD M)"); ax.set_ylabel("Count"); ax.legend(fontsize=8)

plt.suptitle("Distribution of Key Financial Variables", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.savefig("/tmp/hist.png", dpi=130, bbox_inches="tight"); plt.show()
print(" Histograms saved")

 Histograms saved

In [11]:
plt.figure(figsize=(10,5))
sector_order = sorted(df["Sector"].unique())
data = [df[df["Sector"]==s]["Net_Profit"].dropna().values for s in sector_order]
bp = plt.boxplot(data, labels=sector_order, patch_artist=True, widths=0.5,
                 medianprops={"color":"black","linewidth":2})
for patch, c in zip(bp["boxes"], ["steelblue","seagreen","coral","goldenrod","mediumpurple"]):
    patch.set_facecolor(c); patch.set_alpha(0.7)
plt.title("Net Profit Distribution by Sector", fontsize=13, fontweight="bold")
plt.ylabel("Net Profit (USD M)"); plt.grid(axis="y", alpha=0.4); plt.tight_layout()
plt.savefig("/tmp/box.png", dpi=130, bbox_inches="tight"); plt.show()
print(" Boxplots saved")

 Boxplots saved

In [12]:
num_cols = ["Revenue","COGS","Gross_Profit","Op_Expenses","EBIT",
            "Net_Profit","Total_Assets","Total_Debt","Profit_Margin","Debt_Ratio","ROA"]
plt.figure(figsize=(11,8))
sns.heatmap(df[num_cols].corr(), annot=True, fmt=".2f", cmap="coolwarm",
            linewidths=0.4, annot_kws={"size":8})
plt.title("Correlation Heatmap — Financial Features", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig("/tmp/heatmap.png", dpi=130, bbox_inches="tight"); plt.show()
print(" Heatmap saved")

 Heatmap saved

In [13]:
plt.figure(figsize=(9,6))
palette = {"Technology":"steelblue","Healthcare":"seagreen",
           "Finance":"coral","Energy":"goldenrod","Retail":"mediumpurple"}
for sector, group in df.groupby("Sector"):
    plt.scatter(group["Revenue"], group["Net_Profit"],
                label=sector, alpha=0.55, s=20, color=palette[sector])
plt.xlabel("Revenue (USD M)", fontsize=11); plt.ylabel("Net Profit (USD M)", fontsize=11)
plt.title("Revenue vs Net Profit by Sector", fontsize=13, fontweight="bold")
plt.legend(markerscale=2); plt.grid(alpha=0.3); plt.tight_layout()
plt.savefig("/tmp/scatter.png", dpi=130, bbox_inches="tight"); plt.show()
print(" Scatter saved")

 Scatter saved

## Step 8 — Train / Test Split  (80% train · 20% test)

In [14]:
FEATURES = ["Revenue","COGS","Gross_Profit","Op_Expenses","EBIT",
            "Interest_Exp","EBT","Total_Assets","Total_Debt","Equity",
            "Employees","Market_Cap","Sector_Code","Region_Code",
            "Credit_Code","Profit_Margin","Debt_Ratio","ROA"]
TARGET = "Net_Profit"

X = df[FEATURES]; y = df[TARGET]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

print(f" Training samples : {len(X_train)}")
print(f"   Testing  samples : {len(X_test)}")
print(f"   Features used    : {len(FEATURES)}")

 Training samples : 220
   Testing  samples : 55
   Features used    : 18

## Step 9 – XGBoost Model

Train an XGBoost regressor for net profit prediction.

In [15]:
import xgboost as xgb
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# ── Train XGBoost ──────────────────────────────────────────────
xgb_model = xgb.XGBRegressor(
    n_estimators     = 500,
    learning_rate    = 0.05,
    max_depth        = 6,
    subsample        = 0.8,
    colsample_bytree = 0.8,
    reg_alpha        = 0.1,
    reg_lambda       = 1.0,
    random_state     = 42,
    eval_metric      = "rmse",
    early_stopping_rounds = 30,
    verbosity        = 0,
)
xgb_model.fit(
    X_train, y_train,
    eval_set=[(X_test, y_test)],
    verbose=False
)
print(f" XGBoost trained in {xgb_model.best_iteration} rounds (early stop)")

# ── Evaluate ───────────────────────────────────────────────────
xgb_pred = xgb_model.predict(X_test)
xgb_r2   = r2_score(y_test, xgb_pred)
xgb_mae  = mean_absolute_error(y_test, xgb_pred)
xgb_rmse = float(np.sqrt(mean_squared_error(y_test, xgb_pred)))
xgb_rating = "Excellent" if xgb_r2>0.90 else "Good" if xgb_r2>0.75 else "Moderate" if xgb_r2>0.50 else "Weak"

print("=" * 44)
print("       XGBOOST PERFORMANCE REPORT")
print("=" * 44)
print(f"  R² Score : {xgb_r2:.4f}  ({xgb_r2*100:.1f}% variance explained)")
print(f"  MAE      : ${xgb_mae:.2f} M")
print(f"  RMSE     : ${xgb_rmse:.2f} M")
print(f"  Rating   : {xgb_rating}")
print("=" * 44)

# ── Feature Importance ─────────────────────────────────────────
import matplotlib.pyplot as plt
fi = pd.Series(xgb_model.feature_importances_, index=FEATURES).sort_values(ascending=True).tail(10)
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].barh(fi.index, fi.values, color="steelblue", edgecolor="black")
axes[0].set_title("XGBoost — Top 10 Feature Importance (Gain)", fontweight="bold")
axes[0].set_xlabel("Importance Score")
axes[0].grid(axis="x", alpha=0.3)

axes[1].scatter(y_test, xgb_pred, alpha=0.45, s=18, color="steelblue")
lim = [min(y_test.min(), xgb_pred.min()), max(y_test.max(), xgb_pred.max())]
axes[1].plot(lim, lim, "r--", linewidth=1.5, label="Perfect fit")
axes[1].set_xlabel("Actual Net Profit (USD M)")
axes[1].set_ylabel("Predicted Net Profit (USD M)")
axes[1].set_title(f"XGBoost — Actual vs Predicted  R²={xgb_r2:.4f}", fontweight="bold")
axes[1].legend(); axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.savefig("/tmp/xgb_eval.png", dpi=130, bbox_inches="tight")
plt.show()
print(" XGBoost evaluation chart saved")

 XGBoost trained in 355 rounds (early stop)
============================================
       XGBOOST PERFORMANCE REPORT
============================================
  R² Score : 0.9650  (96.5% variance explained)
  MAE      : $33.72 M
  RMSE     : $51.51 M
  Rating   : Excellent
============================================
 XGBoost evaluation chart saved

## Step 10 – LightGBM Model

Train a LightGBM regressor and compare its performance with XGBoost.

In [16]:
import lightgbm as lgb
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# ── Train LightGBM ─────────────────────────────────────────────
lgb_model = lgb.LGBMRegressor(
    n_estimators     = 500,
    learning_rate    = 0.05,
    num_leaves       = 64,
    max_depth        = -1,
    feature_fraction = 0.8,
    bagging_fraction = 0.8,
    bagging_freq     = 5,
    min_child_samples= 20,
    reg_alpha        = 0.1,
    reg_lambda       = 1.0,
    random_state     = 42,
    verbosity        = -1,
)
lgb_model.fit(
    X_train, y_train,
    eval_set=[(X_test, y_test)],
    callbacks=[lgb.early_stopping(30, verbose=False), lgb.log_evaluation(period=-1)]
)
print(f" LightGBM trained in {lgb_model.best_iteration_} rounds (early stop)")

# ── Evaluate ───────────────────────────────────────────────────
lgb_pred = lgb_model.predict(X_test)
lgb_r2   = r2_score(y_test, lgb_pred)
lgb_mae  = mean_absolute_error(y_test, lgb_pred)
lgb_rmse = float(np.sqrt(mean_squared_error(y_test, lgb_pred)))
lgb_rating = "Excellent" if lgb_r2>0.90 else "Good" if lgb_r2>0.75 else "Moderate" if lgb_r2>0.50 else "Weak"

print("=" * 44)
print("      LIGHTGBM PERFORMANCE REPORT")
print("=" * 44)
print(f"  R² Score : {lgb_r2:.4f}  ({lgb_r2*100:.1f}% variance explained)")
print(f"  MAE      : ${lgb_mae:.2f} M")
print(f"  RMSE     : ${lgb_rmse:.2f} M")
print(f"  Rating   : {lgb_rating}")
print("=" * 44)

# ── Feature Importance ─────────────────────────────────────────
fi_lgb = pd.Series(lgb_model.feature_importances_, index=FEATURES).sort_values(ascending=True).tail(10)
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].barh(fi_lgb.index, fi_lgb.values, color="seagreen", edgecolor="black")
axes[0].set_title("LightGBM — Top 10 Feature Importance (Split Count)", fontweight="bold")
axes[0].set_xlabel("Importance Score")
axes[0].grid(axis="x", alpha=0.3)

axes[1].scatter(y_test, lgb_pred, alpha=0.45, s=18, color="seagreen")
lim = [min(y_test.min(), lgb_pred.min()), max(y_test.max(), lgb_pred.max())]
axes[1].plot(lim, lim, "r--", linewidth=1.5, label="Perfect fit")
axes[1].set_xlabel("Actual Net Profit (USD M)")
axes[1].set_ylabel("Predicted Net Profit (USD M)")
axes[1].set_title(f"LightGBM — Actual vs Predicted  R²={lgb_r2:.4f}", fontweight="bold")
axes[1].legend(); axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.savefig("/tmp/lgb_eval.png", dpi=130, bbox_inches="tight")
plt.show()
print(" LightGBM evaluation chart saved")

 LightGBM trained in 95 rounds (early stop)
============================================
      LIGHTGBM PERFORMANCE REPORT
============================================
  R² Score : 0.9254  (92.5% variance explained)
  MAE      : $41.92 M
  RMSE     : $75.21 M
  Rating   : Excellent
============================================
 LightGBM evaluation chart saved

## Step 10C — Model Comparison: XGBoost vs LightGBM

In [17]:
# ── Model Comparison: XGBoost vs LightGBM ────────────────────
model_names = ["XGBoost", "LightGBM"]
r2_scores   = [xgb_r2,  lgb_r2]
mae_scores  = [xgb_mae, lgb_mae]
rmse_scores = [xgb_rmse, lgb_rmse]
bar_colors  = ["#DD8452", "#55A868"]

fig, axes = plt.subplots(1, 3, figsize=(14, 5))
fig.suptitle("Model Comparison: XGBoost vs LightGBM — Net Profit Prediction",
             fontsize=13, fontweight="bold")

for ax, vals, title, higher_better, fmt in [
    (axes[0], r2_scores,   "R² Score (higher = better)",   True,  "{:.4f}"),
    (axes[1], mae_scores,  "MAE — USD M (lower = better)", False, "${:.1f}M"),
    (axes[2], rmse_scores, "RMSE — USD M (lower = better)",False, "${:.1f}M"),
]:
    bars = ax.bar(model_names, vals, color=bar_colors, edgecolor="black", width=0.45)
    best = max(vals) if higher_better else min(vals)
    for bar, val in zip(bars, vals):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + max(vals)*0.01,
                fmt.format(val), ha="center", va="bottom", fontsize=10, fontweight="bold")
        if val == best:
            bar.set_edgecolor("gold"); bar.set_linewidth(3)
    ax.set_title(title, fontweight="bold", fontsize=10)
    ax.set_ylabel(title.split("(")[0].strip())
    ax.grid(axis="y", alpha=0.3)
    ax.set_ylim(0, max(vals) * 1.18)

plt.tight_layout()
plt.savefig("/tmp/model_compare.png", dpi=130, bbox_inches="tight")
plt.show()
print(" Model comparison chart saved")

print()
print("=" * 55)
print(f"{'Model':<18} {'R²':>8} {'MAE':>12} {'RMSE':>12} {'Rating':>10}")
print("-" * 55)
for name, r, m, rm in zip(model_names, r2_scores, mae_scores, rmse_scores):
    rating = "Excellent" if r>0.90 else "Good" if r>0.75 else "Moderate" if r>0.50 else "Weak"
    print(f"{name:<18} {r:>8.4f} {m:>10.2f}M {rm:>10.2f}M {rating:>10}")
print("=" * 55)
print("  ★ Gold border = best model for that metric")

 Model comparison chart saved

=======================================================
Model                    R²          MAE         RMSE     Rating
-------------------------------------------------------
XGBoost              0.9650      33.72M      51.51M  Excellent
LightGBM             0.9254      41.92M      75.21M  Excellent
=======================================================
  ★ Gold border = best model for that metric

## Step 11 — Automated Financial Insights

In [18]:
avg_margin      = df["Profit_Margin"].mean() * 100
avg_roa         = df["ROA"].mean() * 100
avg_debt        = df["Debt_Ratio"].mean()
high_lev        = (df["Debt_Ratio"] > 0.5).mean() * 100
top_sector      = df.groupby("Sector")["Net_Profit"].mean().idxmax()
worst_sector    = df.groupby("Sector")["Net_Profit"].mean().idxmin()
best_co         = df.loc[df["Net_Profit"].idxmax(), "Company"]
rev_profit_corr = df["Revenue"].corr(df["Net_Profit"])

_models = [("XGBoost",  xgb_r2, xgb_mae, xgb_rmse),
           ("LightGBM", lgb_r2, lgb_mae, lgb_rmse)]
_best = max(_models, key=lambda x: x[1])

insights = [
    f"Average Profit Margin is {avg_margin:.1f}% — "
    f"{'above' if avg_margin>15 else 'below'} the 15% industry benchmark.",
    f"'{top_sector}' is the best-performing sector. "
    f"'{worst_sector}' is the lowest-performing sector.",
    f"Average ROA is {avg_roa:.2f}%. "
    f"{(df['ROA']>0).mean()*100:.0f}% of companies have positive ROA.",
    f"{high_lev:.1f}% of companies carry a Debt Ratio above 0.50, "
    f"indicating elevated leverage risk.",
    f"Highest net profit company: {best_co}.",
    f"Revenue-Net Profit correlation = {rev_profit_corr:.3f} "
    f"({'strong' if rev_profit_corr>0.7 else 'moderate'} positive relationship).",
    f"Best ML Model: {_best[0]} - R2={_best[1]:.4f}, MAE=${_best[2]:.1f}M, RMSE=${_best[3]:.1f}M.",
]

print("AUTOMATED FINANCIAL INSIGHTS")
print(chr(8212) * 58)
for i, ins in enumerate(insights, 1):
    print(f"\n{i}. {ins}")

AUTOMATED FINANCIAL INSIGHTS
——————————————————————————————————————————————————————————

1. Average Profit Margin is 16.2% — above the 15% industry benchmark.

2. 'Healthcare' is the best-performing sector. 'Finance' is the lowest-performing sector.

3. Average ROA is 8.16%. 97% of companies have positive ROA.

4. 26.5% of companies carry a Debt Ratio above 0.50, indicating elevated leverage risk.

5. Highest net profit company: Company_241.

6. Revenue-Net Profit correlation = 0.648 (moderate positive relationship).

7. Best ML Model: XGBoost - R2=0.9650, MAE=$33.7M, RMSE=$51.5M.

## Step 12 — Financial Visualizations

In [19]:
sec = df.groupby("Sector")[["Revenue","Gross_Profit","Net_Profit"]].mean().round(1)
sec.plot(kind="bar", figsize=(10,5), width=0.7, edgecolor="black",
         color=["steelblue","seagreen","coral"])
plt.title("Average Revenue, Gross Profit & Net Profit by Sector", fontsize=13, fontweight="bold")
plt.ylabel("USD Million"); plt.xlabel(""); plt.xticks(rotation=15)
plt.legend(loc="upper right"); plt.grid(axis="y", alpha=0.3); plt.tight_layout()
plt.savefig("/tmp/sector_bar.png", dpi=130, bbox_inches="tight"); plt.show()
print(" Sector bar chart saved")

 Sector bar chart saved

In [20]:
trend = df.groupby("Year")[["Revenue","Net_Profit","Op_Expenses"]].mean().round(1)
fig, ax = plt.subplots(figsize=(10,5))
for col, c, m in [("Revenue","steelblue","o"),("Net_Profit","seagreen","s"),("Op_Expenses","coral","^")]:
    ax.plot(trend.index, trend[col], color=c, marker=m, linewidth=2, markersize=6,
            label=col.replace("_"," "))
ax.set_title("Year-Wise Financial Trend (2019–2023)", fontsize=13, fontweight="bold")
ax.set_xlabel("Year"); ax.set_ylabel("Avg USD Million"); ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("/tmp/trend.png", dpi=130, bbox_inches="tight"); plt.show()
print(" Trend chart saved")

 Trend chart saved

In [21]:
ratios = df.groupby("Sector")[["Profit_Margin","Debt_Ratio"]].mean()
fig, axes = plt.subplots(1, 2, figsize=(12,5))
fig.suptitle("Financial Ratios by Sector", fontsize=13, fontweight="bold")
colors_r = ["steelblue","seagreen","coral","goldenrod","mediumpurple"]

for ax, (col, title) in zip(axes, [
        ("Profit_Margin","Profit Margin"),
        ("Debt_Ratio","Debt Ratio (risk >0.5)")]):
    ax.bar(ratios.index, ratios[col], color=colors_r, alpha=0.85, edgecolor="black")
    if col == "Debt_Ratio":
        ax.axhline(0.5, color="red", linestyle="--", linewidth=1.5, label="Risk threshold 0.5")
        ax.legend()
    ax.set_title(title, fontweight="bold")
    ax.set_xticklabels(ratios.index, rotation=15); ax.grid(axis="y", alpha=0.3)

plt.tight_layout()
plt.savefig("/tmp/ratios.png", dpi=130, bbox_inches="tight"); plt.show()
print(" Ratios chart saved")

 Ratios chart saved

In [22]:
credit_counts = df["Credit_Rating"].value_counts()
credit_order  = [c for c in ["AAA","AA","A","BBB","BB","B"] if c in credit_counts.index]
credit_counts = credit_counts.reindex(credit_order)
pie_colors    = ["#1a9850","#66bd63","#a6d96a","#fdae61","#f46d43","#d73027"]

plt.figure(figsize=(7,7))
plt.pie(credit_counts.values, labels=credit_counts.index, autopct="%1.1f%%",
        colors=pie_colors[:len(credit_counts)], startangle=90,
        wedgeprops={"edgecolor":"white","linewidth":1.5})
plt.title("Credit Rating Distribution", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig("/tmp/credit_pie.png", dpi=130, bbox_inches="tight"); plt.show()
print(" Credit pie chart saved")

 Credit pie chart saved

## Step 13 – Generate AI Narrative Report using Gemini API.

In [23]:
# Paste your Gemini API key here
GEMINI_API_KEY = "AIza..."    # Replace with your key from https://aistudio.google.com/app/apikey

sector_table = df.groupby("Sector").agg(
    Avg_Revenue=("Revenue","mean"),
    Avg_Profit=("Net_Profit","mean"),
    Avg_Margin=("Profit_Margin","mean")
).round(2).to_string()

insight_text = "\n".join([f"  {i+1}. {ins}" for i, ins in enumerate(insights)])

prompt = (
    "You are a professional financial analyst. Write a structured executive financial report "
    "(~400 words) using the data below. Use professional tone, be specific with numbers.\n\n"
    f"PORTFOLIO DATA:\n"
    f"  Companies     : {len(df)} companies across 5 sectors (2019-2023)\n"
    f"  Avg Revenue   : ${df['Revenue'].mean():.1f}M\n"
    f"  Avg Net Profit: ${df['Net_Profit'].mean():.1f}M\n"
    f"  Profit Margin : {df['Profit_Margin'].mean()*100:.2f}%\n"
    f"  Avg Debt Ratio: {df['Debt_Ratio'].mean():.3f}\n"
    f"  Avg ROA       : {df['ROA'].mean()*100:.2f}%\n"
    f"  Best ML Model : {_best[0]} (R2={_best[1]:.4f}, MAE=${_best[2]:.1f}M, RMSE=${_best[3]:.1f}M)\n"
    f"  XGBoost R2    : {xgb_r2:.4f}   LightGBM R2: {lgb_r2:.4f}\n\n"
    f"SECTOR BREAKDOWN:\n{sector_table}\n\n"
    f"KEY INSIGHTS:\n{insight_text}\n\n"
    "Use these headings: EXECUTIVE SUMMARY | SECTOR ANALYSIS | PROFITABILITY & RISK | "
    "ML MODEL RESULTS | RECOMMENDATIONS | CONCLUSION"
)

try:
    genai.configure(api_key=GEMINI_API_KEY)
    model_ai  = genai.GenerativeModel("gemini-1.5-flash")
    response  = model_ai.generate_content(prompt)
    ai_report = response.text
    print("Gemini AI report generated!\n")
    print(ai_report)
except Exception as e:
    print(f"Gemini API not available ({e})")
    print("Using built-in fallback report.\n")
    ai_report = (
        "EXECUTIVE SUMMARY\n"
        f"This report analyses {len(df)} companies across 5 sectors (2019-2023). "
        f"Average revenue is ${df['Revenue'].mean():.1f}M with net profit of "
        f"${df['Net_Profit'].mean():.1f}M ({df['Profit_Margin'].mean()*100:.1f}% margin).\n\n"
        "SECTOR ANALYSIS\n"
        "Technology and Healthcare show the strongest profitability. "
        "Energy and Retail face higher cost pressures and thinner margins.\n\n"
        f"PROFITABILITY & RISK\n"
        f"Average ROA is {df['ROA'].mean()*100:.2f}%. "
        f"{(df['Debt_Ratio']>0.5).mean()*100:.0f}% of companies carry Debt Ratio > 0.50.\n\n"
        f"ML MODEL RESULTS\n"
        f"XGBoost R2={xgb_r2:.4f}, LightGBM R2={lgb_r2:.4f}. "
        f"Best: {_best[0]} (R2={_best[1]:.4f}, MAE=${_best[2]:.1f}M).\n\n"
        "RECOMMENDATIONS\n"
        "- Prioritise investment in high-ROA sectors (Technology, Healthcare)\n"
        "- Implement debt restructuring for Debt Ratio > 0.5 companies\n"
        "- Expand model with macroeconomic indicators\n\n"
        "CONCLUSION\n"
        "The portfolio shows resilient financial characteristics. "
        "AI-driven analytics will enhance decision accuracy and reporting speed."
    )
    print(ai_report)

WARNING:tornado.access:400 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1939.22ms

Gemini API not available (400 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: API key not valid. Please pass a valid API key.)
Using built-in fallback report.

EXECUTIVE SUMMARY
This report analyses 275 companies across 5 sectors (2019-2023). Average revenue is $2521.8M with net profit of $375.9M (16.2% margin).

SECTOR ANALYSIS
Technology and Healthcare show the strongest profitability. Energy and Retail face higher cost pressures and thinner margins.

PROFITABILITY & RISK
Average ROA is 8.16%. 27% of companies carry Debt Ratio > 0.50.

ML MODEL RESULTS
XGBoost R2=0.9650, LightGBM R2=0.9254. Best: XGBoost (R2=0.9650, MAE=$33.7M).

RECOMMENDATIONS
- Prioritise investment in high-ROA sectors (Technology, Healthcare)
- Implement debt restructuring for Debt Ratio > 0.5 companies
- Expand model with macroeconomic indicators

CONCLUSION
The portfolio shows resilient financial characteristics. AI-driven analytics will enhance decision accuracy and reporting speed.

## Step 14 – Create Interactive Dashboard

In [24]:
import json, base64
from IPython.display import IFrame, HTML, display

records = df[[
    "Company","Year","Sector","Region","Credit_Rating",
    "Revenue","COGS","Gross_Profit","Op_Expenses","Interest_Exp",
    "Net_Profit","Total_Assets","Total_Debt",
    "Profit_Margin","Debt_Ratio","ROA"
]].copy()
records.columns = [
    "company","year","sector","region","credit",
    "revenue","cogs","gross_profit","op_expenses","interest_exp",
    "net_profit","total_assets","total_debt",
    "profit_margin","debt_ratio","roa"
]
records_json = records.to_json(orient="records")

# Load HTML template (self-contained, no server needed)
html_template = open("/content/Financial_Dashboard.html").read() if False else None

# Build HTML inline
import textwrap
_HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>FinSight Dashboard</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:'Segoe UI',sans-serif;background:#0a0c14;color:#e0e0e0;font-size:14px}
.topbar{background:linear-gradient(135deg,#0d1117,#111827);padding:16px 24px;border-bottom:1px solid #1e2433}
.topbar h1{font-size:20px;color:#00d4ff;letter-spacing:1px}
.topbar p{font-size:11px;color:#555;margin-top:2px}
.filters{display:flex;flex-wrap:wrap;gap:10px;padding:12px 24px;background:#0d1017;border-bottom:1px solid #1e2433;align-items:center}
.filters label{font-size:11px;color:#888}
.filters select{background:#12151f;color:#e0e0e0;border:1px solid #2a2d3a;border-radius:6px;padding:5px 10px;font-size:12px;cursor:pointer}
#resetBtn{background:#00d4ff22;border:1px solid #00d4ff55;color:#00d4ff;padding:5px 14px;border-radius:6px;cursor:pointer;font-size:12px;font-weight:600}
#countBadge{margin-left:auto;font-size:11px;color:#555;background:#12151f;border:1px solid #1e2433;padding:4px 10px;border-radius:20px}
.kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;padding:16px 24px}
.kpi{background:#12151f;border-radius:10px;padding:14px;border:1px solid #1e2433;border-top:3px solid var(--c)}
.kpi .lbl{font-size:10px;color:#888;text-transform:uppercase;letter-spacing:1px;margin-bottom:5px}
.kpi .val{font-size:22px;font-weight:700;color:var(--c)}
.kpi .sub{font-size:10px;color:#444;margin-top:3px}
.grid2{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;padding:0 24px 14px}
.grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;padding:0 24px 14px}
.card{background:#12151f;border-radius:10px;padding:16px;border:1px solid #1e2433}
.card h3{font-size:11px;color:#888;text-transform:uppercase;letter-spacing:1px;margin-bottom:2px}
.card p{font-size:10px;color:#333;margin-bottom:10px}
canvas{max-height:200px}
.tw{margin:0 24px 32px;border-radius:10px;border:1px solid #1e2433;overflow-x:auto}
table{width:100%;border-collapse:collapse;font-size:12px}
thead{background:#12151f}
th{padding:9px 11px;text-align:left;color:#00d4ff;font-weight:600;white-space:nowrap;border-bottom:1px solid #1e2433}
tbody tr:nth-child(even){background:#0d1017}
td{padding:6px 11px;white-space:nowrap}
.tag{padding:2px 7px;border-radius:20px;font-size:10px;font-weight:600}
.s-Technology{background:#00d4ff22;color:#00d4ff}
.s-Healthcare{background:#06d6a022;color:#06d6a0}
.s-Finance{background:#7b61ff22;color:#7b61ff}
.s-Energy{background:#ffd16622;color:#ffd166}
.s-Retail{background:#ff6b6b22;color:#ff6b6b}
.c-AAA{background:#1a985022;color:#1a9850}.c-AA{background:#66bd6322;color:#66bd63}
.c-A{background:#a6d96a22;color:#a6d96a}.c-BBB{background:#fdae6122;color:#fdae61}
.c-BB{background:#f46d4322;color:#f46d43}.c-B{background:#d7302722;color:#d73027}
</style>
</head>
<body>
<div class="topbar">
  <h1>■ FinSight — AI Financial Dashboard</h1>
  <p>275 Companies · 5 Sectors · 4 Regions · 2019–2023 | Models: XGBoost &amp; LightGBM</p>
</div>
<div class="filters">
  <label>Sector</label>
  <select id="fSector"><option value="">All Sectors</option></select>
  <label>Year</label>
  <select id="fYear"><option value="">All Years</option></select>
  <label>Region</label>
  <select id="fRegion"><option value="">All Regions</option></select>
  <label>Credit</label>
  <select id="fCredit"><option value="">All Ratings</option></select>
  <button id="resetBtn">Reset Filters</button>
  <span id="countBadge">Showing — records</span>
</div>
<div class="kpis">
  <div class="kpi" style="--c:#00d4ff"><div class="lbl">Avg Revenue</div><div class="val" id="kR">—</div><div class="sub">USD Million per company</div></div>
  <div class="kpi" style="--c:#06d6a0"><div class="lbl">Avg Net Profit</div><div class="val" id="kP">—</div><div class="sub">USD Million per company</div></div>
  <div class="kpi" style="--c:#ffd166"><div class="lbl">Profit Margin</div><div class="val" id="kM">—</div><div class="sub">Net profit / revenue</div></div>
  <div class="kpi" style="--c:#ff6b6b"><div class="lbl">Avg Debt Ratio</div><div class="val" id="kD">—</div><div class="sub">Total debt / total assets</div></div>
  <div class="kpi" style="--c:#7b61ff"><div class="lbl">Avg ROA</div><div class="val" id="kROA">—</div><div class="sub">Net profit / total assets</div></div>
</div>
<div class="grid2">
  <div class="card"><h3>Revenue, Gross Profit & Net Profit by Sector</h3><p>Average USD Million</p><canvas id="c1"></canvas></div>
  <div class="card"><h3>Year-Wise Financial Trend</h3><p>2019–2023 average USD Million</p><canvas id="c2"></canvas></div>
  <div class="card"><h3>Revenue Breakdown (Portfolio Avg)</h3><p>Cost & profit composition</p><canvas id="c3"></canvas></div>
  <div class="card"><h3>Profit Margin & Debt Ratio by Sector</h3><p>Dual-axis ratio chart</p><canvas id="c4"></canvas></div>
</div>
<div class="grid3">
  <div class="card"><h3>Credit Rating Distribution</h3><p>&nbsp;</p><canvas id="c5"></canvas></div>
  <div class="card"><h3>Profit Margin % by Sector</h3><p>Average margin per sector</p><canvas id="c6"></canvas></div>
  <div class="card"><h3>Revenue vs Net Profit Scatter</h3><p>By sector (filtered)</p><canvas id="c7"></canvas></div>
</div>
<div class="tw">
  <table><thead><tr>
    <th>Company</th><th>Year</th><th>Sector</th><th>Region</th><th>Credit</th>
    <th>Revenue ($M)</th><th>Net Profit ($M)</th><th>Profit Margin</th><th>Debt Ratio</th><th>ROA</th>
  </tr></thead><tbody id="tbody"></tbody></table>
</div>
<script>
const RAW=RECORDS_PLACEHOLDER;
const SECS=["Technology","Healthcare","Finance","Energy","Retail"];
const YRS=[2019,2020,2021,2022,2023];
const SC={Technology:"rgba(0,212,255,0.8)",Healthcare:"rgba(6,214,160,0.8)",Finance:"rgba(123,97,255,0.8)",Energy:"rgba(255,209,102,0.8)",Retail:"rgba(255,107,107,0.8)"};
const fS=document.getElementById("fSector"),fY=document.getElementById("fYear"),fR=document.getElementById("fRegion"),fC=document.getElementById("fCredit");
SECS.forEach(s=>fS.insertAdjacentHTML("beforeend","<option>"+s+"</option>"));
YRS.forEach(y=>fY.insertAdjacentHTML("beforeend","<option>"+y+"</option>"));
[...new Set(RAW.map(r=>r.region))].sort().forEach(r=>fR.insertAdjacentHTML("beforeend","<option>"+r+"</option>"));
["AAA","AA","A","BBB","BB","B"].forEach(c=>fC.insertAdjacentHTML("beforeend","<option>"+c+"</option>"));
const avg=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
const gf=()=>{const fs=fS.value,fy=fY.value,fr=fR.value,fc=fC.value;return RAW.filter(r=>(!fs||r.sector===fs)&&(!fy||r.year==fy)&&(!fr||r.region===fr)&&(!fc||r.credit===fc));};
const AX={x:{ticks:{color:"#888",font:{size:9}},grid:{color:"#1e2433"}},y:{ticks:{color:"#888",font:{size:9}},grid:{color:"#1e2433"}}};
const OPT={responsive:true,maintainAspectRatio:true,plugins:{legend:{labels:{color:"#aaa",font:{size:10}}}},scales:AX};
const mk=(id,type,data,extra={})=>new Chart(document.getElementById(id),{type,data,options:{...OPT,...extra}});
const C1=mk("c1","bar",{labels:SECS,datasets:[{label:"Revenue",backgroundColor:"rgba(0,212,255,0.75)",data:[]},{label:"Gross Profit",backgroundColor:"rgba(6,214,160,0.75)",data:[]},{label:"Net Profit",backgroundColor:"rgba(123,97,255,0.75)",data:[]}]});
const C2=mk("c2","line",{labels:YRS,datasets:[{label:"Revenue",borderColor:"#00d4ff",backgroundColor:"rgba(0,212,255,0.1)",data:[],tension:0.3,fill:true},{label:"Net Profit",borderColor:"#06d6a0",backgroundColor:"rgba(6,214,160,0.1)",data:[],tension:0.3,fill:true},{label:"Op Expenses",borderColor:"#ff6b6b",backgroundColor:"rgba(255,107,107,0.1)",data:[],tension:0.3,fill:true}]});
const C3=mk("c3","bar",{labels:["Portfolio Avg"],datasets:[{label:"COGS",backgroundColor:"rgba(255,107,107,0.75)",data:[],stack:"s"},{label:"Op Expenses",backgroundColor:"rgba(255,209,102,0.75)",data:[],stack:"s"},{label:"Interest",backgroundColor:"rgba(248,150,30,0.75)",data:[],stack:"s"},{label:"Net Profit",backgroundColor:"rgba(6,214,160,0.75)",data:[],stack:"s"}]},{scales:{x:{stacked:true,ticks:{color:"#888"},grid:{color:"#1e2433"}},y:{stacked:true,ticks:{color:"#888"},grid:{color:"#1e2433"}}}});
const C4=mk("c4","bar",{labels:SECS,datasets:[{label:"Profit Margin",yAxisID:"y",backgroundColor:"rgba(0,212,255,0.75)",data:[]},{label:"Debt Ratio",yAxisID:"y1",backgroundColor:"rgba(255,107,107,0.75)",data:[]}]},{scales:{x:{ticks:{color:"#888"},grid:{color:"#1e2433"}},y:{type:"linear",position:"left",ticks:{color:"#888"},grid:{color:"#1e2433"},title:{display:true,text:"Margin",color:"#888"}},y1:{type:"linear",position:"right",ticks:{color:"#888"},grid:{drawOnChartArea:false},title:{display:true,text:"Debt Ratio",color:"#888"}}}});
const C5=mk("c5","pie",{labels:[],datasets:[{data:[],backgroundColor:["#1a9850","#66bd63","#a6d96a","#fdae61","#f46d43","#d73027"],borderWidth:2,borderColor:"#0a0c14"}]},{scales:{}});
const C6=mk("c6","bar",{labels:SECS,datasets:[{label:"Avg Profit Margin %",backgroundColor:Object.values(SC),data:[]}]});
const C7=mk("c7","scatter",{datasets:[]});
function upd(){
  const d=gf();
  document.getElementById("countBadge").textContent="Showing "+d.length+" records";
  document.getElementById("kR").textContent="$"+avg(d.map(r=>r.revenue)).toFixed(0)+"M";
  document.getElementById("kP").textContent="$"+avg(d.map(r=>r.net_profit)).toFixed(0)+"M";
  document.getElementById("kM").textContent=(avg(d.map(r=>r.profit_margin))*100).toFixed(1)+"%";
  document.getElementById("kD").textContent=avg(d.map(r=>r.debt_ratio)).toFixed(3);
  document.getElementById("kROA").textContent=(avg(d.map(r=>r.roa))*100).toFixed(2)+"%";
  C1.data.datasets[0].data=SECS.map(s=>avg(d.filter(r=>r.sector===s).map(r=>r.revenue)).toFixed(1));
  C1.data.datasets[1].data=SECS.map(s=>avg(d.filter(r=>r.sector===s).map(r=>r.gross_profit)).toFixed(1));
  C1.data.datasets[2].data=SECS.map(s=>avg(d.filter(r=>r.sector===s).map(r=>r.net_profit)).toFixed(1));
  C1.update();
  C2.data.datasets[0].data=YRS.map(y=>avg(d.filter(r=>r.year===y).map(r=>r.revenue)).toFixed(1));
  C2.data.datasets[1].data=YRS.map(y=>avg(d.filter(r=>r.year===y).map(r=>r.net_profit)).toFixed(1));
  C2.data.datasets[2].data=YRS.map(y=>avg(d.filter(r=>r.year===y).map(r=>r.op_expenses)).toFixed(1));
  C2.update();
  const ma=v=>avg(d.map(r=>r[v])).toFixed(1);
  C3.data.datasets[0].data=[ma("cogs")];C3.data.datasets[1].data=[ma("op_expenses")];
  C3.data.datasets[2].data=[ma("interest_exp")];C3.data.datasets[3].data=[ma("net_profit")];
  C3.update();
  C4.data.datasets[0].data=SECS.map(s=>(avg(d.filter(r=>r.sector===s).map(r=>r.profit_margin))*100).toFixed(2));
  C4.data.datasets[1].data=SECS.map(s=>avg(d.filter(r=>r.sector===s).map(r=>r.debt_ratio)).toFixed(3));
  C4.update();
  const cc={};d.forEach(r=>{cc[r.credit]=(cc[r.credit]||0)+1});
  const co=["AAA","AA","A","BBB","BB","B"].filter(c=>cc[c]);
  C5.data.labels=co;C5.data.datasets[0].data=co.map(c=>cc[c]);C5.update();
  C6.data.datasets[0].data=SECS.map(s=>(avg(d.filter(r=>r.sector===s).map(r=>r.profit_margin))*100).toFixed(2));C6.update();
  C7.data.datasets=SECS.map(s=>({label:s,backgroundColor:SC[s],data:d.filter(r=>r.sector===s).map(r=>({x:+r.revenue.toFixed(1),y:+r.net_profit.toFixed(1)}))}));C7.update();
  document.getElementById("tbody").innerHTML=d.map(r=>`<tr>
    <td>${r.company}</td><td>${r.year}</td>
    <td><span class="tag s-${r.sector}">${r.sector}</span></td>
    <td>${r.region}</td>
    <td><span class="tag c-${r.credit}">${r.credit}</span></td>
    <td>$${(+r.revenue).toFixed(1)}</td>
    <td style="color:${r.net_profit>=0?'#06d6a0':'#ff6b6b'}">${(+r.net_profit).toFixed(1)}</td>
    <td>${(r.profit_margin*100).toFixed(1)}%</td>
    <td style="color:${r.debt_ratio>0.5?'#ff6b6b':'#e0e0e0'}">${(+r.debt_ratio).toFixed(3)}</td>
    <td>${(r.roa*100).toFixed(2)}%</td>
  </tr>`).join("");
}
[fS,fY,fR,fC].forEach(el=>el.addEventListener("change",upd));
document.getElementById("resetBtn").addEventListener("click",()=>{[fS,fY,fR,fC].forEach(el=>el.value="");upd();});
upd();
</script>
</body></html>"""

html_final = _HTML_TEMPLATE.replace("RECORDS_PLACEHOLDER", records_json)

# Save file
with open("/content/Financial_Dashboard.html", "w", encoding="utf-8") as f:
    f.write(html_final)
print("Financial_Dashboard.html saved to /content/Financial_Dashboard.html")

# FIX: Encode as base64 data URI — works without any HTTP server
b64 = base64.b64encode(html_final.encode("utf-8")).decode("utf-8")
data_uri = f"data:text/html;base64,{b64}"

# Button to open in new tab
display(HTML(f'''
<div style="margin:16px 0">
  <a href="{data_uri}" target="_blank"
     style="background:#00d4ff;color:#000;padding:10px 22px;border-radius:8px;
            font-weight:bold;text-decoration:none;font-size:14px;display:inline-block">
    Open Interactive Dashboard (New Tab)
  </a>
  <span style="color:#888;font-size:12px;margin-left:12px">No server needed — opens instantly</span>
</div>
'''))

# Inline preview in Colab output cell
display(HTML('<p style="color:#06d6a0;font-size:12px;margin:8px 0">Inline Preview (scroll to explore)</p>'))
display(IFrame(src=data_uri, width="100%", height="720"))

Financial_Dashboard.html saved to /content/Financial_Dashboard.html

## Step 15 — Export Full PDF Report

In [25]:
def build_pdf(path="/content/Financial_Report.pdf"):
    doc = SimpleDocTemplate(path, pagesize=A4,
                            leftMargin=0.8*inch, rightMargin=0.8*inch,
                            topMargin=0.8*inch,  bottomMargin=0.8*inch)
    st    = getSampleStyleSheet()
    story = []
    title_s = ParagraphStyle("TT", fontSize=20, fontName="Helvetica-Bold",
                              textColor=colors.HexColor("#003366"),
                              alignment=TA_CENTER, spaceAfter=6)
    h1 = ParagraphStyle("H1", fontSize=13, fontName="Helvetica-Bold",
                         textColor=colors.HexColor("#003366"), spaceBefore=12, spaceAfter=4)
    h2 = ParagraphStyle("H2", fontSize=11, fontName="Helvetica-Bold",
                         textColor=colors.HexColor("#0055a5"), spaceBefore=8, spaceAfter=3)
    body = ParagraphStyle("BD", fontSize=10, leading=15, spaceAfter=5, alignment=TA_JUSTIFY)

    def add_img(src, w=5.8*inch, h=3.2*inch, cap=""):
        try: story.append(RLImage(src, width=w, height=h))
        except Exception as ex: story.append(Paragraph(f"[Image not available: {ex}]", body))
        if cap:
            story.append(Paragraph(f"<i>{cap}</i>",
                ParagraphStyle("cap", fontSize=8, textColor=colors.grey,
                               alignment=TA_CENTER, spaceAfter=4)))
        story.append(Spacer(1, 6))

    story += [Spacer(1, 0.9*inch),
              Paragraph("AI-Based Automated", title_s),
              Paragraph("Financial Report Generation System", title_s),
              Spacer(1, 0.25*inch),
              HRFlowable(width="100%", thickness=2, color=colors.HexColor("#003366")),
              Spacer(1, 0.15*inch)]
    cover = [
        ["Companies Analysed", f"{len(df):,}  ({df['Sector'].nunique()} sectors)"],
        ["Years Covered",      f"{df['Year'].min()} - {df['Year'].max()}"],
        ["ML Models",          f"XGBoost (R2={xgb_r2:.4f}) vs LightGBM (R2={lgb_r2:.4f})  |  Best: {_best[0]}"],
        ["AI Narrative",       "Gemini AI (Google)"],
        ["Report Generated",   "2025"],
    ]
    ct = Table(cover, colWidths=[2.3*inch, 4.1*inch])
    ct.setStyle(TableStyle([
        ("BACKGROUND", (0,0),(0,-1), colors.HexColor("#003366")),
        ("TEXTCOLOR",  (0,0),(0,-1), colors.white),
        ("FONTNAME",   (0,0),(-1,-1), "Helvetica-Bold"),
        ("FONTSIZE",   (0,0),(-1,-1), 10),
        ("ROWBACKGROUNDS",(1,0),(1,-1),[colors.HexColor("#eaf2ff"),colors.white]),
        ("GRID",  (0,0),(-1,-1), 0.4, colors.lightgrey),
        ("PADDING",(0,0),(-1,-1), 8),
    ]))
    story += [ct, PageBreak()]

    story += [Paragraph("Key Performance Indicators", h1),
              HRFlowable(width="100%", thickness=1, color=colors.HexColor("#0055a5")),
              Spacer(1, 8)]
    kpi = [
        ["Metric","Value","Metric","Value"],
        ["Avg Revenue",   f"${df['Revenue'].mean():,.1f} M",    "Avg Net Profit", f"${df['Net_Profit'].mean():,.1f} M"],
        ["Profit Margin", f"{df['Profit_Margin'].mean()*100:.2f}%", "Avg Debt Ratio", f"{df['Debt_Ratio'].mean():.3f}"],
        ["Avg ROA",       f"{df['ROA'].mean()*100:.2f}%",       "High Leverage",  f"{(df['Debt_Ratio']>0.5).mean()*100:.0f}% of companies"],
        [f"Best Model ({_best[0]})", f"R2={_best[1]:.4f}", "Model MAE", f"${_best[2]:.1f} M"],
        [f"XGBoost R2={xgb_r2:.4f}", f"LightGBM R2={lgb_r2:.4f}", "Total Records", f"{len(df):,}"],
    ]
    kt = Table(kpi, colWidths=[1.9*inch,1.5*inch,1.9*inch,1.5*inch])
    kt.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,0), colors.HexColor("#003366")),
        ("TEXTCOLOR",     (0,0),(-1,0), colors.white),
        ("FONTNAME",      (0,0),(-1,-1), "Helvetica-Bold"),
        ("FONTSIZE",      (0,0),(-1,-1), 10),
        ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.HexColor("#f0f7ff"),colors.white]),
        ("GRID",   (0,0),(-1,-1), 0.4, colors.lightgrey),
        ("ALIGN",  (1,0),(1,-1), "CENTER"), ("ALIGN",(3,0),(3,-1),"CENTER"),
        ("PADDING",(0,0),(-1,-1), 7),
    ]))
    story += [kt, PageBreak()]

    story += [Paragraph("Automated Financial Insights", h1),
              HRFlowable(width="100%", thickness=1, color=colors.HexColor("#0055a5")),
              Spacer(1, 8)]
    for ins in insights:
        story += [Paragraph(f"&#9658; {ins}", body), Spacer(1, 4)]

    story += [Spacer(1, 10),
              Paragraph("AI-Generated Narrative Report (Gemini AI)", h1),
              HRFlowable(width="100%", thickness=1, color=colors.HexColor("#0055a5")),
              Spacer(1, 8)]
    for line in ai_report.strip().split("\n"):
        if not line.strip(): story.append(Spacer(1, 4)); continue
        is_head = line.strip().isupper() and len(line.strip()) < 55
        story.append(Paragraph(line.strip(), h2 if is_head else body))
    story.append(PageBreak())

    story += [Paragraph("ML Models: XGBoost & LightGBM", h1),
              HRFlowable(width="100%", thickness=1, color=colors.HexColor("#0055a5")),
              Spacer(1, 6),
              Paragraph(
                  "XGBoost and LightGBM are gradient-boosting tree ensembles trained to predict "
                  "Net Profit from 18 financial features with early stopping to prevent overfitting. "
                  "Feature importance charts reveal which financial metrics drive predictions most. "
                  "Both models were compared on R2, MAE, and RMSE.",
                  body),
              Spacer(1, 8)]
    for src, cap in [
        ("/tmp/xgb_eval.png",     "Figure A: XGBoost - Feature Importance & Actual vs Predicted"),
        ("/tmp/lgb_eval.png",     "Figure B: LightGBM - Feature Importance & Actual vs Predicted"),
        ("/tmp/model_compare.png","Figure C: XGBoost vs LightGBM - R2, MAE, RMSE Comparison"),
    ]:
        add_img(src, cap=cap)
    story.append(PageBreak())

    story += [Paragraph("Data Visualizations", h1),
              HRFlowable(width="100%", thickness=1, color=colors.HexColor("#0055a5")),
              Spacer(1, 8)]
    for src, cap in [
        ("/tmp/sector_bar.png", "Figure 1: Avg Revenue, Gross Profit & Net Profit by Sector"),
        ("/tmp/trend.png",      "Figure 2: Year-Wise Financial Trend (2019-2023)"),
        ("/tmp/heatmap.png",    "Figure 3: Correlation Heatmap - Financial Features"),
        ("/tmp/ratios.png",     "Figure 4: Profit Margin & Debt Ratio by Sector"),
        ("/tmp/scatter.png",    "Figure 5: Revenue vs Net Profit by Sector"),
        ("/tmp/credit_pie.png", "Figure 6: Credit Rating Distribution"),
    ]:
        add_img(src, cap=cap)
    story.append(PageBreak())

    story += [Paragraph("Conclusion & Future Enhancements", h1),
              HRFlowable(width="100%", thickness=1, color=colors.HexColor("#0055a5")),
              Spacer(1, 8)]
    for pt in [
        f"End-to-end pipeline on {len(df):,} company records across 5 sectors and 5 years.",
        f"XGBoost R2={xgb_r2:.4f} vs LightGBM R2={lgb_r2:.4f}. Best model: {_best[0]} (MAE=${_best[2]:.1f}M).",
        "Gemini AI automatically produced a professional narrative financial report.",
        "Interactive HTML dashboard opens inline in Colab via data URI - no server required.",
        "Future: Real-time market data integration, Streamlit deployment, anomaly detection.",
    ]:
        story += [Paragraph(f"&#9658; {pt}", body), Spacer(1, 5)]

    story += [Spacer(1, 30),
              HRFlowable(width="100%", thickness=0.5, color=colors.grey),
              Paragraph("AI-Based Financial Report Generation System | 2025",
                  ParagraphStyle("ft", fontSize=8, textColor=colors.grey, alignment=TA_CENTER))]

    doc.build(story)
    print(f"PDF saved: {path}")
    return path

build_pdf()

PDF saved: /content/Financial_Report.pdf

'/content/Financial_Report.pdf'

## Step 16 — Download All Output Files

In [ ]:
from google.colab import files
files.download("/content/Financial_Report.pdf")
files.download("/content/Financial_Dashboard.html")
files.download("financial_dataset.csv")
print(" All 3 files downloading — check your browser downloads folder")

✅ All 3 files downloading — check your browser downloads folder

# Net Profit Prediction

In [30]:
new_company = pd.DataFrame({
    'Revenue': [500000],
    'COGS': [300000],
    'Gross_Profit': [200000],
    'Op_Expenses': [50000],
    'EBIT': [150000],
    'Interest_Exp': [10000],
    'EBT': [140000],
    'Total_Assets': [1000000],
    'Total_Debt': [300000],
    'Equity': [700000],
    'Employees': [100],
    'Market_Cap': [2000000],
    'Sector_Code': [1],
    'Region_Code': [1],
    'Credit_Code': [2],
    'Profit_Margin': [0.28],
    'Debt_Ratio': [0.30],
    'ROA': [0.14]
})

In [31]:
pred = best_model.predict(new_company)

print(f"Predicted Net Profit: ₹{pred[0]:,.2f}")

Predicted Net Profit: ₹1,087.28

# Conclusion

This project successfully developed an automated financial report generation system using machine learning techniques. After preprocessing and analyzing the financial data, XGBoost and LightGBM models were used to predict company net profit and compare their performance.

The project also generated visualizations, dashboards, and financial summaries that can help users understand company performance more effectively. Overall, this work shows how machine learning can reduce manual financial analysis and assist in making data-driven decisions.

Future improvements may include using real company financial statements, adding more financial indicators, and deploying the system as a web application.